HRMS.Web/Controllers/EmployeePaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using HRMS.Core.Model;
using HRMS.Core.Services.Interfaces;
using HRMS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters.Xml;

namespace HRMS.Web.Controllers
{
    public class EmployeePaymentsController : Controller
    {
        private readonly IPayrollService service;
        private readonly ICompanyService companyService;

        public EmployeePaymentsController(IPayrollService service, ICompanyService companyService)
        {
            this.service = service;
            this.companyService = companyService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid Id)
        {
            var listResult = await service.GetGeneratedPayrolls(Id);
            ViewBag.CompanyId = Id;
            if (!listResult.IsSuccessful)
            {
                ModelState.AddModelError("", listResult.Message);
                return View(new List<CompanyPayrollViewModel>());
            }

            return View(listResult.Result.Select(Parse));
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid Id)
        {
            var companyResult = await companyService.GetByIdAsync(Id);

            if (!companyResult.IsSuccessful)
            {
                ModelState.AddModelError("", companyResult.Message);
            }
            return View(new CompanyPayrollViewModel()
            {
                CompanyId = Id,
                CompanyName = companyResult.Result?.Name
            });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            var companyResult = await service.GetByIdAsync(Id);

            if (!companyResult.IsSuccessful)
            {
                ModelState.AddModelError("", companyResult.Message);
                return View(new CompanyPayrollViewModel()
                {
                    Id = Id
                });
            }
            return View(Parse(companyResult.Result));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CompanyPayrollViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await service.GenerateAsync(model.CompanyId, model.SegmentId);
                if (!result.IsSuccessful)
                {
                    ModelState.AddModelError("", result.Message);
                    return View(model);
                }
                return RedirectToAction("Index", new { Id = model.CompanyId });
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CompanyPayrollViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await service.PayCompanyPayrollAsync(model.Id, model.IsPayed);
                if (!result.IsSuccessful)
                {
                    ModelState.AddModelError("", result.Message);
                    return View(model);
                }
                return RedirectToAction("Index", new { Id = model.CompanyId });
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(Guid id)
        {
            GenericViewModel result = new GenericViewModel();
            if (id == Guid.Empty)
            {
                result.ErrorMessage = "Please select payment";
            }

            var linkResult = await service.DeleteCompanyPayrollAsync(id);

            if (linkResult.IsSuccessful)
            {
                result.IsSuccessful = true;
            }
            else
            {
                result.ErrorMessage = linkResult.Message;
            }
            return Json(result);
        }
        public async Task<IActionResult> GetPayrollEmployees(Guid id)
        {
            var toSendModel = new CompanyPayrollEmployeesJsonModel() { IsSuccessful = true };
            var result = await service.GetPayrollEmployees(id);

            if (result.IsSuccessful)
                toSendModel.Items = result.Result.Select(Parse);
            else
            {
                toSendModel.IsSuccessful = false;
                toSendModel.ErrorMessage = result.Message;
            }
            return Json(toSendModel);
        }
        private static PayrollEmployeetDto Parse(EmployeeCompanyPayroll model)
        {
            return new PayrollEmployeetDto
            {
                Id = model.Id,
                Amount = model.BrutoAmount,
                Employee = $"{model.Employee.Name} {model.Employee.LastName}",
                EndDate = model.OrganigramEmployee.EndDate,
                StartDate = model.OrganigramEmployee.StartDate,
                Neto = model.NetoAmount,
                Position = model.OrganigramEmployee.Organigram.Name
            };
        }
        private static CompanyPayrollViewModel Parse(CompanyPayroll model)
        {
            return new CompanyPayrollViewModel
            {
                Id = model.Id,
                IsPayed = model.IsPayed,
                CompanyName = model.Company.Name,
                Segment = model.PayrollSegment.Name,
                TotalAmount = model.TotalAmounBruto,
                Season = model.PayrollSegment.PayrollSeason.Name,
                CompanyId = model.CompanyId,
                SeasonId = model.PayrollSegment.PayrollSeasonId,
                SegmentId = model.PayrollSegmentId
            };
        }

    }
}

HRMS.Web/Controllers/JsonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HRMS.Core.Model;
using HRMS.Core.Services.Interfaces;
using HRMS.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace HRMS.Web.Controllers
{
    public class JsonController : Controller
    {
        private readonly IJsonService service;
        private readonly ICompanyService companyService;
        private readonly ICompanyDepartamentService companyDepartmentService;
        private readonly IPayrollSegmentService payrollSegmentService;

        public JsonController(IJsonService service, 
            ICompanyService companyService, ICompanyDepartamentService companySiteService,IPayrollSegmentService payrollSegmentService)
        {
            this.service = service;
            this.companyService = companyService;
            this.companyDepartmentService = companySiteService;
            this.payrollSegmentService = payrollSegmentService;
        }
        #region reference
        [HttpGet]
        public async Task<IActionResult> GetCountries(string search, int page)
        {

            var serviceResponse = await service.GetAllCountriesAsync(search);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetRegions(string search, int page, int? countryId)
        {

            var serviceResponse = await service.GetAllRegionsAsync(search, countryId);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetCities(string search, int page, int? countryId, int? regionId)
        {

            var serviceResponse = await service.GetAllCitiesAsync(search, countryId, regionId);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetDepartments(string search, int page, Guid companyId)
        {

            var serviceResponse = await service.GetAllDepartmentsAsync(search, companyId);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetPayrollSeasons(string search, int page)
        {

            var serviceResponse = await service.GetPayrollSeasonsAsync(search);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }
        [HttpGet]
        public async Task<IActionResult> GetPayrollSegments(int seasonId,string search, int page)
        {

            var serviceResponse = await payrollSegmentService.GetAllAsync(seasonId);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

       

        [HttpGet]
        public IActionResult GetYears(string search, int page)
        {
            var last5Years = from n in Enumerable.Range(0, 80)
                             select DateTime.Now.Year - 18 - n;


            var result = new JsonGenericModel() { IsSuccessful = true };

            if (!string.IsNullOrEmpty(search))
            {
                last5Years = last5Years.Where(a => a.ToString().Contains(search.ToLower()));
            }
            result.Items = last5Years.Select(a => new SelectDataDTO { Id = a.ToString(), Text = a.ToString() });

            return Json(result);
        }

        [HttpGet]
        public IActionResult GetDays(string search, int page, int year, int month)
        {
            var result = new JsonGenericModel() { IsSuccessful = true };

            var date = new DateTime(year, month, 1).AddMonths(1).AddDays(-1);

            var list = new List<SelectDataDTO>();
            for (int i = 1; i <= date.Day; i++)
            {
                list.Add(new SelectDataDTO
                {
                    Id = i.ToString(),
                    Text = i.ToString()
                });
            }
            result.Items = list;
            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetContacts(string search, int page)
        {
            var serviceResponse = await service.GetAllContactsAsync(search);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetCompanySites(string search, int page, Guid? companyId)
        {
            var serviceResponse = await service.GetCompanyDepartmentsAsync(search, companyId);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> GetOrganigrams(string search, int page, Guid? companySiteId)
        {
            var serviceResponse = await service.GetOrganigramsAsync(search, companySiteId);

            var result = new JsonGenericModel();
            if (serviceResponse.IsSuccessful)
            {
                result.IsSuccessful = true;
                result.Items = serviceResponse.Result.Select(a => Parse(a));
            }
            else
            {
                result.ErrorMessage = serviceResponse.Message;
            }

            return Json(result);
        }
        #endregion


        [HttpGet]
        public async Task<IActionResult> GetCompanyOrganigrams(Guid companyId)
        {
            var result = new CompanyOrganigramJsonModel();

            var organigramResponse = await service.GetCompanyOrganigramsAsync(companyId);
            var employeeResponse = await service.GetCompanyEmployesAsync(companyId);
            var companyResponse = await companyService.GetByIdAsync(companyId);
            var companySites = await companyDepartmentService.GetAllAsync(companyId);

            if (organigramResponse.IsSuccessful && employeeResponse.IsSuccessful && companyResponse.IsSuccessful && companySites.IsSuccessful)
            {
                result.IsSuccessful = true;

                var items = (from org in organigramResponse.Result
                             join emp in employeeResponse.Result.Where(a => !a.EndDate.HasValue || a.EndDate.Value >= DateTime.Now) on org.Id equals emp.OrganigramId into ps
                             from dt in ps.DefaultIfEmpty()
                             select new
                             {
                                 org.Id,
                                 Name = dt?.Employee == null ? "" : string.Join(dt.Employee.Name, " : ", dt.Employee.LastName),
                                 Title = org.Name,
                                 RespondsTo = org.RespondsToId,
                                 org.IsCeo,
                                 org.CompanyDepartament,
                                 org.CompanyDepartamentId
                             }).ToList();
                var list = new List<OrganigramDto>();
                // add the company
                var company = new OrganigramDto
                {
                    Id = Guid.Empty,
                    Name = companyResponse.Result.Name,
                    Title = "Company",
                    Children = new List<OrganigramDto>()
                };

                var ceoData = items.FirstOrDefault(a => a.CompanyDepartamentId == null && a.IsCeo);

                var companyCeo = new OrganigramDto() { Id = ceoData.Id, Name = ceoData.Name, Title = ceoData.Title, Children = new List<OrganigramDto>() };

                list.Add(companyCeo);

                //Bord

HRMS.Web/Views/EmployeePayments/Create.cshtml
@model HRMS.Web.Models.CompanyPayrollViewModel

@{
    ViewData["Title"] = "Create";
}

<partial name="_header" />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input asp-for="Id" hidden />
            <input asp-for="CompanyId" hidden />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input readonly asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Season" class="control-label"></label>
                <select asp-for="SeasonId" class="form-control">
                    @if (Model.SeasonId > 0)
                    {

                        <option selected value="@Model.SeasonId">@Model.Season</option>
                    }
                </select>
                <span asp-validation-for="SeasonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Segment" class="control-label"></label>
                <select asp-for="SegmentId" class="form-control">
                    @if (Model.SegmentId > 0)
                    {

                        <option selected value="@Model.SegmentId">@Model.Segment</option>
                    }
                </select>
                <span asp-validation-for="SegmentId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
            $(function () {

                $('#SeasonId').select2({
                        placeholder: 'Select an option',
                        ajax: {
                            url: '@Url.Action("GetPayrollSeasons", "Json")',
                            data: function (params) {
                                var query = {
                                    search: params.term,
                                    page: params.page || 1
                                }
                                return query;
                            },
                            processResults: function (data) {
                                return {
                                    results: data.items
                                };
                            }
                        }
                    }).on('change', function () {
                        PrepareSegment("");
                    });

                function PrepareSegment(value) {

                    $('#SegmentId').val(value).select2({
                        placeholder: 'Select an option',
                        ajax: {
                            url: '@Url.Action("GetPayrollSegments", "Json")',
                            data: function (params) {
                                var query = {
                                    search: params.term,
                                    page: params.page || 1,
                                    seasonId: $("#SeasonId").val()
                                }
                                return query;
                            },
                            processResults: function (data) {
                                return {
                                    results: data.items
                                };
                            }
                        }
                    });

                }


                PrepareSegment('@Model.SegmentId');
            });

    </script>
}

HRMS.Web/Views/EmployeePayments/Edit.cshtml
@model HRMS.Web.Models.CompanyPayrollViewModel

@{
    ViewData["Title"] = "Edit";
}

<partial name="_header" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input asp-for="Id" hidden />
            <input asp-for="CompanyId" hidden />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input readonly asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Season" class="control-label"></label>
                <select asp-for="SeasonId" class="form-control">
                    @if (Model.SeasonId > 0)
                    {

                        <option selected value="@Model.SeasonId">@Model.Season</option>
                    }
                </select>
                <span asp-validation-for="SeasonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Segment" class="control-label"></label>
                <select asp-for="SegmentId" class="form-control">
                    @if (Model.SegmentId > 0)
                    {

                        <option selected value="@Model.SegmentId">@Model.Segment</option>
                    }
                </select>
                <span asp-validation-for="SegmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsPayed" class="control-label"></label>
                <input readonly asp-for="IsPayed" class="form-control" />
                <span asp-validation-for="IsPayed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table display">
            <thead>
                <tr>
                    <th>
                        Position
                    </th>
                    <th>
                        Employee
                    </th>
                    <th>
                        Start Date
                    </th>
                    <th>
                        EndDate
                    </th>
                    <th>
                        Bruto
                    </th>
                    <th>
                        Neto
                    </th>

                    <th class="no-sort"></th>
                </tr>
            <tbody></tbody>
        </table>
    </div>

</div>
@section Scripts{
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        $(function () {
            var table = $(".table").DataTable({
                ajax: {
                    url: "@Url.Action("GetPayrollEmployees", "EmployeePayments", new { id = Model.Id })",
                    dataSrc: 'items'
                },
                "columns": [
                    { "data": "position" },
                    { "data": "employee" },
                    { "data": "startDate" },
                    { "data": "endDate" },
                    { "data": "amount" },
                    { "data": "neto" }
                ]

                , "columnDefs": [
                    { targets: 'no-sort', orderable: false }
                ]
            });
        });
    </script>
}

HRMS.Web/Views/EmployeePayments/Index.cshtml
@model IEnumerable<HRMS.Web.Models.CompanyPayrollViewModel>

@{
    ViewData["Title"] = "Employee Payment Managements";
}

<div class="row">
    <div class="col-md-12">
        <h2 class="d-inline">Employee Payment Managements</h2>
        <a asp-action="Create" asp-route-id="@ViewBag.CompanyId" class="btn btn-success float-right">Create New</a>
    </div>
    <hr />
</div>
<hr />
<div class="list-header">
</div>
<main>
    <table class="table display">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CompanyName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Segment)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Season)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsPayed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalAmount)
                </th>
                <th class="no-sort">Actions</th>
            </tr>
        </thead>
        <tbody>
           
            @foreach (var item in Model)
            {
                <tr role="row" class="rowlink">
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Segment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Season)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsPayed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </td>
                    <td class="actions">
                        @*<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info ">Details </a>*@

                        <a asp-action="Edit" asp-route-id="@item.Id" class=" btn btn-primary">Edit </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger delete">Delete </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Delete Item
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this item ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>
</main>
@section Scripts{


    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(function () {
            var table = $(".table").DataTable({
                "columnDefs": [{ targets: 'no-sort', orderable: false }]
            });

            $('#confirm-delete').on('show.bs.modal', function (e) {
                $(".modal-body").empty().html(" Are you sure you want to delete this item ?");
               var url= $(e.relatedTarget).attr('href');
                $(this).find('.btn-ok').attr('href',url);
            });

            $(".btn-ok").on("click", function (event) {
                event.preventDefault();
                var url = $(this).attr("href");
                $.ajax
                    ({
                        type: "POST",
                        url: url,
                        success: function (data) {
                            console.log(data);
                            if (data.isSuccessful) {
                                location.reload();
                            }
                            else {
                                $(".modal-body").empty().html(data.errorMessage);
                            }
                        }
                    });
                return false;
            });
        });

    </script>
}

HRMS.Web/Views/EmployeePayments/_form.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

HRMS.Web/Views/EmployeePayments/_header.cshtml
<div class="row ">
    <div class="col-md-11">
        <h2 class="d-inline">Regions - @ViewData["Title"]</h2>
    </div>
    <div class="col-md-1">
        <a asp-action="Index" class="btn btn-light">Back</a>
    </div>
</div>
<hr />
<div class="list-header"></div>